#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
#
Name     : R-FNN
Version  : 1.1.3.2
Release  : 51
URL      : https://cran.r-project.org/src/contrib/FNN_1.1.3.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/FNN_1.1.3.2.tar.gz
Summary  : Fast Nearest Neighbor Search Algorithms and Applications
Group    : Development/Tools
License  : GPL-2.0+ LGPL-2.1
Requires: R-FNN-lib = %{version}-%{release}
Requires: R-FNN-license = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
including KNN classification, regression and information measures are implemented.

%package lib
Summary: lib components for the R-FNN package.
Group: Libraries
Requires: R-FNN-license = %{version}-%{release}

%description lib
lib components for the R-FNN package.


%package license
Summary: license components for the R-FNN package.
Group: Default

%description license
license components for the R-FNN package.


%prep
%setup -q -n FNN
cd %{_builddir}/FNN

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1679414403

%install
export SOURCE_DATE_EPOCH=1679414403
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-FNN
cp %{_builddir}/FNN/inst/COPYRIGHTS %{buildroot}/usr/share/package-licenses/R-FNN/d17434c50ecdf04221f28b0c886a217d32314c84 || :
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/FNN/COPYRIGHTS
/usr/lib64/R/library/FNN/DESCRIPTION
/usr/lib64/R/library/FNN/INDEX
/usr/lib64/R/library/FNN/Meta/Rd.rds
/usr/lib64/R/library/FNN/Meta/features.rds
/usr/lib64/R/library/FNN/Meta/hsearch.rds
/usr/lib64/R/library/FNN/Meta/links.rds
/usr/lib64/R/library/FNN/Meta/nsInfo.rds
/usr/lib64/R/library/FNN/Meta/package.rds
/usr/lib64/R/library/FNN/NAMESPACE
/usr/lib64/R/library/FNN/R/FNN
/usr/lib64/R/library/FNN/R/FNN.rdb
/usr/lib64/R/library/FNN/R/FNN.rdx
/usr/lib64/R/library/FNN/help/AnIndex
/usr/lib64/R/library/FNN/help/FNN.rdb
/usr/lib64/R/library/FNN/help/FNN.rdx
/usr/lib64/R/library/FNN/help/aliases.rds
/usr/lib64/R/library/FNN/help/paths.rds
/usr/lib64/R/library/FNN/html/00Index.html
/usr/lib64/R/library/FNN/html/R.css

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/FNN/libs/FNN.so
/usr/lib64/R/library/FNN/libs/FNN.so.avx2
/usr/lib64/R/library/FNN/libs/FNN.so.avx512

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-FNN/d17434c50ecdf04221f28b0c886a217d32314c84
